### PR TITLE
Added QAModel and FAQBot

### PR DESCRIPTION
**Pull request by jonathanbgn**
- QAModel loads the model in memory from [TensorFlow Hub](https://tfhub.dev/google/universal-sentence-encoder/4) and has a simple API to find the best answer to a question.
- FAQBot uses QAModel to answer questions. I didn't test it on my side as I'm not familiar with Microsoft's botbuilder.

Caution: the model is quite big (916MB) and will be downloaded from TensorFlow Hub the first time it is loaded (and then cached on disk). We also need at least as much RAM to load the model into memory. I'm not so sure about memory limits in Heroku? @geekyme

### CODE REVIEW

**Comment by geekyme** [comment]
Nice thanks for this @jonathanbgn ! heroku has a limit of 512MB. https://devcenter.heroku.com/articles/limits

We could merge and see what happens? 💥

**Review by geekyme — APPROVED** [review]

**Comment by jonathanbgn** [comment]
Sure let's do this, pretty sure this will crash then :laughing:

A solution could be to use the [lite version](https://tfhub.dev/google/universal-sentence-encoder-lite/2), but this wouldn't be as accurate and I'll need to do some more adjustments as it seems it's using an older version of TensorFlow.

**Review by erickhun — APPROVED** [review]
this is really nice @jonathanbgn !

@geekyme let's merge and see what happen

**Comment by geekyme** [comment]
I'll post the logs in a bit

**Comment by geekyme** [comment]
There we go:

```
2020-09-20T09:45:03.371324+00:00 heroku[web.1]: Starting process with command `uvicorn app:app --host=0.0.0.0 --port=${PORT:-8000}`
2020-09-20T09:45:05.459073+00:00 app[web.1]: INFO:     Uvicorn running on http://0.0.0.0:26891 (Press CTRL+C to quit)
2020-09-20T09:45:05.459184+00:00 app[web.1]: INFO:     Started parent process [4]
2020-09-20T09:45:06.747794+00:00 app[web.1]: 2020-09-20 09:45:06.747702: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /app/.heroku/vendor/lib:/app/.heroku/python/lib:
2020-09-20T09:45:06.747840+00:00 app[web.1]: 2020-09-20 09:45:06.747762: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-20T09:45:06.768030+00:00 app[web.1]: 2020-09-20 09:45:06.767949: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /app/.heroku/vendor/lib:/app/.heroku/python/lib:
2020-09-20T09:45:06.768038+00:00 app[web.1]: 2020-09-20 09:45:06.768005: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-20T09:45:46.898475+00:00 app[web.1]: 2020-09-20 09:45:46.898381: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /app/.heroku/vendor/lib:/app/.heroku/python/lib:
2020-09-20T09:45:46.898497+00:00 app[web.1]: 2020-09-20 09:45:46.898448: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-20T09:45:46.898526+00:00 app[web.1]: 2020-09-20 09:45:46.898499: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (d1dec18a-c722-4303-8111-95aa0ffe65d5): /proc/driver/nvidia/version does not exist
2020-09-20T09:45:46.933834+00:00 app[web.1]: 2020-09-20 09:45:46.933748: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2500070000 Hz
2020-09-20T09:45:46.947477+00:00 app[web.1]: 2020-09-20 09:45:46.947410: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55cb7e0e8760 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-20T09:45:46.947483+00:00 app[web.1]: 2020-09-20 09:45:46.947455: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-20T09:45:54.035189+00:00 app[web.1]: 2020-09-20 09:45:54.034328: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /app/.heroku/vendor/lib:/app/.heroku/python/lib:
2020-09-20T09:45:54.035395+00:00 app[web.1]: 2020-09-20 09:45:54.035347: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-20T09:45:54.035841+00:00 app[web.1]: 2020-09-20 09:45:54.035804: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (d1dec18a-c722-4303-8111-95aa0ffe65d5): /proc/driver/nvidia/version does not exist
2020-09-20T09:45:54.104463+00:00 heroku[web.1]: Process running mem=1040M(199.2%)
2020-09-20T09:45:54.106667+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2020-09-20T09:45:54.379078+00:00 app[web.1]: 2020-09-20 09:45:54.378917: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2500070000 Hz
2020-09-20T09:45:54.400998+00:00 app[web.1]: 2020-09-20 09:45:54.400872: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55c8cc989a70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-20T09:45:54.401008+00:00 app[web.1]: 2020-09-20 09:45:54.400962: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-20T09:45:56.262814+00:00 heroku[web.1]: Process running mem=1280M(250.0%)
2020-09-20T09:45:56.290694+00:00 heroku[web.1]: Error R15 (Memory quota vastly exceeded)
2020-09-20T09:45:56.293068+00:00 heroku[web.1]: Stopping process with SIGKILL
2020-09-20T09:45:56.469102+00:00 heroku[web.1]: Process exited with status 137
2020-09-20T09:45:56.507662+00:00 heroku[web.1]: State changed from starting to crashed
2020-09-20T09:45:56.509995+00:00 heroku[web.1]: State changed from crashed to starting
```

**Comment by jonathanbgn** [comment]
Just as expected, let me implement the lite version then.

**Comment by geekyme** [comment]
👍

**Pull request merged**
